# Generated by Django 4.1.2 on 2022-10-29 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='36 макс.', max_length=36, verbose_name='название категории')),
                ('description', models.CharField(blank=True, help_text='255 макс.', max_length=255, null=True, verbose_name='описание')),
                ('is_published', models.BooleanField(default=False, verbose_name='публикация')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='online_auction.category', verbose_name='родительская категория')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'auction_categories',
                'ordering': ('is_published', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='36 макс.', max_length=36, verbose_name='название лота')),
                ('description', models.CharField(blank=True, help_text='255 макс.', max_length=255, null=True, verbose_name='описание лота')),
                ('article', models.CharField(help_text='16 макс.', max_length=16, unique=True, verbose_name='артикль')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='online_auction.category', verbose_name='категория лота')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'lot',
                'verbose_name_plural': 'lots',
                'db_table': 'auction_lots',
                'ordering': ('owner', 'created_date'),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='36 макс.', max_length=36, verbose_name='имя аукциона')),
                ('buyout_price', models.DecimalField(blank=True, decimal_places=2, help_text='$99999999.99 макс.', max_digits=10, null=True, verbose_name='цена выкупа $')),
                ('start_price', models.DecimalField(decimal_places=2, help_text='$99999999.99 макс.', max_digits=10, verbose_name='стартовая цена $')),
                ('start_date', models.DateTimeField(verbose_name='дата начала')),
                ('end_date', models.DateTimeField(verbose_name='дата закрытия')),
                ('is_started', models.BooleanField(default=False, verbose_name='открыт')),
                ('is_closed', models.BooleanField(default=False, verbose_name='закрыт')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='online_auction.lot', verbose_name='лот')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='победитель')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'db_table': 'auction_events',
                'ordering': ('start_date',),
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='дата ставки')),
                ('bet', models.DecimalField(decimal_places=2, help_text='$99999999.99 макс.', max_digits=10, verbose_name='ставка $')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='online_auction.event', verbose_name='аукцион')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='создатель')),
            ],
            options={
                'verbose_name': 'bet',
                'verbose_name_plural': 'bets',
                'db_table': 'auction_bets',
                'ordering': ('created_date', 'bet'),
            },
        ),
    ]
